# Generated by Django 6.0.1 on 2026-01-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_available_since_user_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='current_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
