# Generated by Django 6.0.1 on 2026-01-25 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_current_lat_user_current_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_lat',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_lng',
        ),
    ]
