# Generated by Django 6.0.2 on 2026-02-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.FloatField(default=12.9716),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.FloatField(default=77.5946),
        ),
    ]
