# Generated by Django 6.0.1 on 2026-01-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakeries', '0002_bakery_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakery',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='bakery_logos/'),
        ),
    ]
