# Generated by Django 6.0.1 on 2026-01-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakeries', '0003_bakery_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakery',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bakery',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
