# Generated by Django 6.0.1 on 2026-01-25 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakeries', '0004_bakery_latitude_bakery_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakery',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='bakery',
            name='longitude',
        ),
    ]
