# Generated by Django 6.0.2 on 2026-02-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakeries', '0005_remove_bakery_latitude_remove_bakery_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakery',
            name='latitude',
            field=models.FloatField(default=12.9716),
        ),
        migrations.AddField(
            model_name='bakery',
            name='longitude',
            field=models.FloatField(default=77.5946),
        ),
    ]
