# Generated by Django 6.0.1 on 2026-02-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakeries', '0006_bakery_latitude_bakery_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakery',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bakery',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
