# Generated by Django 6.0.1 on 2026-01-25 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_features', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TasteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sweet_tooth_level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=5)),
                ('favorite_flavor', models.CharField(choices=[('chocolate', '🍫 Chocolate'), ('vanilla', '🍦 Vanilla'), ('fruit', '🍓 Fruit / Berry'), ('nuts', '🥜 Nutty'), ('spicy', '🌶️ Spiced')], max_length=20)),
                ('texture_preference', models.CharField(choices=[('soft', '☁️ Soft & Spongey'), ('crunchy', '🍪 Crunchy & Crispy'), ('creamy', '🥛 Creamy & Rich')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taste_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
