# Generated by Django 6.0.1 on 2026-01-25 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_features', '0002_tasteprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TasteProfile',
        ),
    ]
