# Generated by Django 6.0.1 on 2026-01-25 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_delivery_lat_order_delivery_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_lat',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_lng',
        ),
    ]
