# Generated by Django 6.0.1 on 2026-02-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_3d',
            field=models.FileField(blank=True, null=True, upload_to='cake_models/'),
        ),
    ]
